spring:
  datasource:
    username: root
    password: cC123456
    url: jdbc:mysql://localhost:3306/ykdb?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.uploadPath}

mybatis:
  mapper-locations: classpath:org/lanqiao/yk/mapper/*.xml
#  type-aliases-package: org.lanqiao.entity

#showSql
logging:
  level:
    com.lanqiao.jd.mapper: DEBUG

web:
  uploadPath: D://tomcatupload